

\documentclass[11pt]{book}   
\usepackage{resDocSty}      % Res Doc .sty file
\captionsetup{figurewithin=none,tablewithin=none} %RH: This works for resetting figure and table numbers for book class though I don't know why. Set fig/table start number to n-1.
\usepackage{graphicx}

\usepackage{Sweave}   % andy add3ed
\usepackage{rotating}    % for sideways table
\usepackage{longtable}


\newcommand{\Bmsy}{B_\mathrm{MSY}}
\newcommand{\umsy}{u_\mathrm{MSY}}
\newcommand{\super}[1]{$^\mathrm{#1}$}

\def\startP{1}                   % page start (default=1)
\def\startF{0}                   % figure start counter (default=0)
\def\startT{0}                   % table start counter (default=0)
\def\bfTh{{\bf \Theta}}  % bold Theta

\renewcommand{\rmdefault}{phv}   % Arial
\renewcommand{\sfdefault}{phv}   % Arial

\newcommand\onefig[2]{    % filename is #1, text is #2
  \begin{figure}[!htp]
  \begin{center}
	\includegraphics[width=6in,height=7in,keepaspectratio=TRUE]{#1.eps} \\  % RH much better control
  %\epsfxsize=6in
  %\epsfbox{#1.eps}
  \end{center}
  \caption{#2 }
  \label{fig:#1} 
  \end{figure}
  %\clearpage
}

\newcommand\twofig[3]{   % figure #1 under #2, caption text #3
  \begin{figure}[!htp]     %  label will be #1
  \centering
  \begin{tabular}{c}
	\includegraphics[width=6in,height=3.5in,keepaspectratio=TRUE]{#1.eps} \\  % RH much better control
	\includegraphics[width=6in,height=3.5in,keepaspectratio=TRUE]{#2.eps}
  \end{tabular}
  \caption{#3}
  \label{fig:#1}
  \end{figure}
  \clearpage
}

\newcommand\threefig[4]{    % figure #1 then #2 then #3, 
  \begin{figure}[!htp]       %  caption text #4, label will be #1
  \centering
  \begin{tabular}{c}
	\includegraphics[width=6in,height=2.5in,keepaspectratio=TRUE]{#1.eps} \\  % RH much better control
	\includegraphics[width=6in,height=2.5in,keepaspectratio=TRUE]{#2.eps} \\
	\includegraphics[width=6in,height=2.5in,keepaspectratio=TRUE]{#3.eps}
  %\vspace{-20mm} 
  %\epsfbox{#1.eps} \\
  %\vspace{-20mm} 
  %\epsfbox{#2.eps} \\
  % \vspace{-20mm} 
  %\epsfbox{#3.eps}
  \end{tabular}
  \caption{#4}
  \label{fig:#1}
  \end{figure}
  \clearpage
}

        % keep.source=TRUE, 


\begin{document}
\setcounter{page}{\startP}
\setcounter{figure}{\startF}
\setcounter{table}{\startT}
\setcounter{secnumdepth}{3}    % To number subsubheadings-ish

\newcounter{prevchapter}
\setcounter{chapter}{6}    % temporary for standalone chapters
\setcounter{prevchapter}{\value{chapter}}
\renewcommand{\thechapter}{\Alph{chapter}} % ditto
\newcommand{\eqnchapter}{\Alph{prevchapter}}


\renewcommand{\thesection}{\thechapter.\arabic{section}}   
\renewcommand{\thetable}{\thechapter.\arabic{table}}    
\renewcommand{\thefigure}{\thechapter.\arabic{figure}}  
\renewcommand{\theequation}{\thechapter.\arabic{equation}}
\renewcommand{\thepage}{\thechapter\arabic{page}}




\lhead{DRAFT -- Non-citable working paper}  % Omit for final ResDoc.
\rhead{CSAP WP 2013/P27}
\lfoot{Appendix \thechapter ~-- Model Results} 
\rfoot{Silvergray Rockfish (CST)} 

\chapter*{Appendix~\thechapter. Model Results}
%\chapter{MCMC Working Results for Silvergray Rockfish}

\newcommand{\numMCMC}{1,000}

\newcommand{\currYear}{2014} % so can include in captions. 

% Text for MPD Run 16 Rwt 3

\section{Introduction}

This Appendix describes the results from the mode of the posterior distribution (MPD) (to compare model estimates to observations), diagnostics of the Markov chain Monte Carlo (MCMC) results, and the MCMC results for the estimated parameters.  The final advice and major outputs are obtained from the MCMC results. Estimates of major quantities and advice to management (such as decision tables) are also presented in the main text.

% Taking next section of text from the Sweave.

\section{Mode of the posterior distribution (MPD) results}

Awatea first determines the MPD for each estimated parameter.  These are then used as the starting points for the MCMC simulations. The MPD fits are shown for the survey indices (Figure~\ref{fig:survIndSer2}), the commercial catch-at-age data (as overlaid age structures in Figures \ref{fig:ageCommFemale1} and \ref{fig:ageCommMale1}), the West Coast Haida Gwaii (WCHG) synoptic survey (Figure~\ref{fig:ageSurvWCHGSynopticFemale1}), the Hecate Strait (HS) synoptic survey (Figure~\ref{fig:ageSurvHSSynopticFemale2}), the Queen Charlotte Sound (QCS) synoptic survey (Figure~\ref{fig:ageSurvQCSoundSynopticFemale3}), and the West Coast Vancouver Island (WCVI) synoptic survey series age data (Figure \ref{fig:ageSurvWCVISynopticFemale4}). The results are sensible and are able to capture the main features of the data sets fairly well. There appears to be relative consistency between the available data sources.

Residuals to the MPD model fits are provided for the six survey indices (Figures \ref{fig:survResWCHGSynoptic} to \ref{fig:survResUSTriennial}), and the five sets of age data (Figures \ref{fig:commAgeResids} and \ref{fig:survAgeResSer4}). These further suggest that the model fits are consistent with the data, as do the mean ages for the two sets of age data (Figure \ref{fig:meanAge}).

Figure \ref{fig:stockRecruit} shows the resulting stock-recruitment function and the MPD values of recruitment over time (though see Figure \ref{fig:recruitsMCMC} for the MCMC values of recruitment). Figure \ref{fig:recDev} shows that the recruitment deviations display no trend over time, and that the auto-correlation function of the deviations appears satisfactory. Figure \ref{fig:selectivity} gives the MPD fits for the selectivities, together with ogive for female maturity. Figure~\ref{fig:exploit} gives the exploitation over time. The values of the log-likelihood and objective functions for the MPD fits are given in Table \ref{tab:like}.

% Silvergray Rockfish CST base case (Run11)
\section{Bayesian MCMC Results}

The MCMC procedure performed 10,000,000 iterations, sampling every 10,000$^\mathrm{th}$ to give 1,000 MCMC samples.  The 1,000 samples were used with no burn-in period (because the MCMC searches started from the MPD values). The quantiles (0.05, 0.50, 0.95) for estimated parameters and derived quantities appear in Tables~\ref{tab:MCMCpar} and \ref{tab:MCMCderived}. In particular, the current year median estimate of $B_{2014}$ is 19,803~t. The median depletion estimate $B_{2014}/B_0$ is  0.559.

MCMC traces show acceptable convergence properties (no trend with increasing sample number) for the estimated parameters (Figure \ref{fig:traceParams}), as does a diagnostic analysis that splits the samples into three segments (Figure \ref{fig:splitChain}). Some of the parameters (e.g., $h$) move from the initial MPD estimate to some other median value.  Pairs plots of the estimated parameters (starting at Figure~\ref{fig:pairs1}) show no undesirable correlations between parameters.  In particular, steepness $h$ and the natural mortality parameters ($M_1$,$M_2$) show little correlation, suggesting that sufficient data exist to estimate these parameters simultaneously.  Trace plots of the derived quantities 'female spawning biomass' (Figure~\ref{fig:traceBiomass}) and recruitment (Figure~\ref{fig:traceRecruits}) also show good convergence properties.  Thus, the MCMC computations seem satisfactory.

Marginal posterior distributions and corresponding priors for the estimated parameters are shown in Figure \ref{fig:pdfParameters}. For some of the parameters (e.g., $M_2$), the model finds enough information to move the posterior distribution away from the prior. The estimate of female natural mortality, $M_1$, shifted slightly higher from 0.06 to 0.062 while male natural mortality, $M_2$, shifted noticeably lower from 0.06 to 0.051. The $h$ posterior basically mirrored the prior. Corresponding summary statistics for the estimated parameters are given in Table \ref{tab:MCMCpar}.


The marginal posterior distribution of vulnerable biomass and catch (Figure~\ref{fig:VBcatch}) shows a decline in the population from 1965 to aprroximately 1992, and a levelling off since then. 
The median spawning biomass relative to unfished equilibrium values (Figure~\ref{fig:BVBnorm}) reached a minimum of 0.513 in 1991 and currently sits at 0.559. 
The recruitment patterns for Silvergray Rockfish show occasional upticks in 1982, 1991, and 2000 (Figure~\ref{fig:recruitsMCMC}). 
Exploitation rates were elevated during various periods around 1965, 1988, 1994, and peaked in 1988 at a median value of 0.103 (Figure~\ref{fig:exploitMCMC}).
A phase plot showing the time-evolution of spawning biomass and exploitation rate relative to $B_\mathrm{MSY}$ and $F_\mathrm{MSY}$ (Figure~\ref{fig:snail}) show a meandering within a good zone (low exploitation, high biomass).

\section{Projection results and decision tables}

Projections were made to evaluate the future behaviour of the population under different levels of constant catch, given the model assumptions.  The projections, starting with the biomass at the beginning of 2014, were made over a range of constant catch strategies (0-3,000~t) for each of the \numMCMC~MCMC samples in the posterior, generating future biomass trends by assuming random recruitment deviations.  Future recruitments were generated through the stock-recruitment function using recruitment deviations drawn randomly from a lognormal distribution with zero mean and constant standard deviation (see Appendix~\eqnchapter{} for full details). Projections were made for 10 years. This time frame was considered to be long enough to satisify the 'long-term' requirement of the Request for Science Information and Advice (Appendix~A), yet short enough for the projected recruitments to be mainly based on individuals spawned before 2014 (and hence already estimated by the model).

Resulting projections of spawning biomass are shown for selected catch strategies (Figure \ref{fig:Bproj}). These suggest that the recent increase in spawning biomass would most likely continue for a catch of 1500~t, which is  larger  than the recent average catch of 1431~t. 

Note that recruitment is drawn from the estimated stock-recruitment curve with lognormal error that has a standard deviation of 0.6 and a mean of zero. However, this approach of average recruitment does not accurately simulate the occasional large recruitment events that have occurred for this stock (Figure~\ref{fig:recruitsMCMC}).

Decision tables give the probabilities of the spawning biomass exceeding the reference points in specified years, calculated by counting the proportion of MCMC samples for which the biomass exceeded the given reference point.

Results for the three $\Bmsy$-based reference points are presented in Tables \ref{tab:LRP}-\ref{tab:Bmsy}. For example, the estimated probability that the stock is in the provisional healthy zone in 2017 under a constant catch strategy of 1,000~t is P$(B_{2017} > 0.8 \Bmsy)=1$ (row '1000' and column '2017' in Table \ref{tab:URP}). 

Table~\ref{tab:Bcurr} provides probabilities that projected spawning biomass $B_t$ will exceed the current-year biomass $B_{2014}$ at the various catch levels. The first column populated by zero values simply means that the current-year biomass will never be greater than itself. Table~\ref{tab:umsy} shows the probabilities of projected exploitation rate $u_t$ exceeding that at MSY ($u_\mathrm{MSY}$).

For the maximum sustainable yield (MSY) calculations, projections were run for 301 values of constant exploitation rate $u_t$ between 0 and 0.3, until an equilibrium yield was reached within a tolerance of 0.01~t (or until 15,000 years had been reached). This was done for each of the \numMCMC~samples.
The lower bound of $u_t$ was reached for  none  of the MCMC samples, and the upper bound was reached by 78 of the samples.
Of the 301,000 projection calculations,  all converged  by 15,000 years.


% Figures from MPD Run 16 Rwt 3
\onefig{survIndSer2}{Survey index values (points) with 95\% confidence intervals (bars) and MPD model fits (curves) for the fishery-independent survey series.}

\onefig{ageCommFemale1}{Observed and predicted commercial proportions-at-age for females. Note that years are not consecutive.}

\onefig{ageCommMale1}{Observed and predicted commercial proportions-at-age for males. Note that years are not consecutive.}

\clearpage 

\twofig{ageSurvWCHGSynopticFemale1}{ageSurvWCHGSynopticMale1}{Observed and predicted proportions-at-age for WCHG synoptic survey.}

\twofig{ageSurvHSSynopticFemale2}{ageSurvHSSynopticMale2}{Observed and predicted proportions-at-age for HS synoptic survey.}

\twofig{ageSurvQCSoundSynopticFemale3}{ageSurvQCSoundSynopticMale3}{Observed and predicted proportions-at-age for QCSound synoptic survey.}

\twofig{ageSurvWCVISynopticFemale4}{ageSurvWCVISynopticMale4}{Observed and predicted proportions-at-age for WCVI synoptic survey.}

\clearpage

\onefig{survResWCHGSynoptic}{Residuals of fits of model to WCHG synoptic survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\onefig{survResHSSynoptic}{Residuals of fits of model to HS synoptic survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\onefig{survResQCSoundSynoptic}{Residuals of fits of model to QCS synoptic survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\clearpage

\onefig{survResWCVISynoptic}{Residuals of fits of model to WCVI synoptic survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\onefig{survResHistoricGBReed}{Residuals of fits of model to Historic GB Reed survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\onefig{survResUSTriennial}{Residuals of fits of model to US Triennial survey series (MPD values). Vertical axes are standardised residuals. The three plots show, respectively, residuals by year of index, residuals relative to predicted index, and normal quantile-quantile plot for residuals (horizontal lines give 5, 25, 50, 75 and 95 percentiles).}

\onefig{commAgeResids}{Residual of fits of model to commercial proportions-at-age data (MPD values).  Vertical axes are standardised residuals. Boxplots show, respectively, residuals by age class, by year of data, and by year of birth (following a cohort through time). Boxes give interquartile ranges, with bold lines representing medians and whiskers extending to the most extreme data point that is $<$1.5 times the interquartile range from the box. Bottom panel is the normal quantile-quantile plot for residuals, with the 1:1 line, though residuals are not expected to be normally distributed because of the likelihood function used; horizontal lines give the 5, 25, 50, 75, and 95 percentiles (for the total of 1550 residuals).}

\clearpage

\onefig{survAgeResSer1}{Residuals of fits of model to proportions-at-age data (MPD values) from WCHG synoptic survey series. Details as for Figure \ref{fig:commAgeResids}, for a total of *** residuals.} % number of years of survey age data * (number age classes -1) * 2

\onefig{survAgeResSer2}{Residuals of fits of model to proportions-at-age data (MPD values) from HS synoptic survey series. Details as for Figure \ref{fig:commAgeResids}, for a total of *** residuals.} % number of years of survey age data * (number age classes -2) * 2

\onefig{survAgeResSer3}{Residuals of fits of model to proportions-at-age data (MPD values) from QCS synoptic survey series. Details as for Figure \ref{fig:commAgeResids}, for a total of *** residuals.} % number of years of survey age data * (number age classes -3) * 2

\onefig{survAgeResSer4}{Residuals of fits of model to proportions-at-age data (MPD values) from WCVI synoptic survey series. Details as for Figure \ref{fig:commAgeResids}, for a total of *** residuals.} % number of years of survey age data * (number age classes -4) * 2

\onefig{meanAge}{Mean ages each year for the data (closed circles) and model estimates (joined open triangles) for the commercial and survey age data.}

\clearpage

\begin{figure}[htp]            %  label will be #1
\centering
\epsfxsize=6in
\begin{tabular}{c}
\vspace{-20mm}\\
\epsfbox{stockRecruit.eps} \\   % \MPDfigdir/
\vspace{-20mm} \\
\epsfbox{recruits.eps}          % \MPDfigdir/
\vspace{-3mm}        % To avoid footer
\end{tabular}
\caption{Top: Deterministic stock-recruit relationship (black curve) and observed values (labelled by year of spawning) using MPD values. Bottom: Recruitment (MPD values of age-1 individuals in year $t$) over time, in 1,000s of age-1 individuals, with a mean of 3,851.5.}
\label{fig:stockRecruit}
\end{figure}

\twofig{recDev}{recDevAcf}{Top: log of the annual recruitment deviations, $\epsilon_t$, where bias-corrected multiplicative deviation is  $\mbox{e}^{\epsilon_t - \sigma_R^2/2}$ where $\epsilon_t \sim \mbox{Normal}(0, \sigma_R^2)$. Bottom: Auto-correlation function of the logged recruitment deviations ($\epsilon_t$), for years 1961-1999 (determined as the first year of commercial age data minus the accumulator age class plus the age for which commercial selectivity for females is 0.5, to the final year that recruitments are calculated minus the age for which commercial selectivity for females is 0.5).}

\onefig{selectivity}{Selectivities for commercial catch (labelled `Gear 1' here) and surveys (all MPD values), with maturity ogive for females indicated by `m'.}

\onefig{exploit}{Exploitation rate (MPD) over time for Silvergray Rockfish along the BC coast.}




\onefig{traceParams}{MCMC traces for the estimated parameters. Grey lines show the \numMCMC~samples for each parameter, solid lines show the cumulative median (up to that sample), and dashed lines show the cumulative 2.5 and 97.5 quantiles.  Red circles are the MPD estimates. For parameters other than $M$ (if estimated), subscripts $\leq 6$ correspond to fishery-independent surveys, and subscripts $\geq 7$ denote the commercial fishery. Parameter notation is described in Appendix~\eqnchapter.}


\onefig{splitChain}{Diagnostic plot obtained by dividing the MCMC chain of \numMCMC~MCMC samples into three segments, and overplotting the cumulative distributions of the first segment (green), second segment (red) and final segment (blue).}

\onefig{pairs1}{Pairs plot of \numMCMC~MCMC samples for 1$^\text{st}$ six parameters. Numbers are the absolute values of the correlation coefficients.}
\onefig{pairs2}{Pairs plot of \numMCMC~MCMC samples for 2$^\text{nd}$ six parameters. Numbers are the absolute values of the correlation coefficients.}
\onefig{pairs3}{Pairs plot of \numMCMC~MCMC samples for 3$^\text{rd}$ six parameters. Numbers are the absolute values of the correlation coefficients.}
\onefig{pairs4}{Pairs plot of \numMCMC~MCMC samples for 4$^\text{th}$ six parameters. Numbers are the absolute values of the correlation coefficients.}
\onefig{pairs5}{Pairs plot of \numMCMC~MCMC samples for 5$^\text{th}$ six parameters. Numbers are the absolute values of the correlation coefficients.}







\onefig{traceBiomass}{MCMC traces for female spawning biomass estimates at five-year intervals.  Note that vertical scales are different for each plot (to show convergence of the MCMC chain, rather than absolute differences in annual values). Grey lines show the \numMCMC~samples for each parameter, solid lines show the cumulative  median (up to that sample), and dashed lines show the cumulative  2.5 and 97.5 quantiles.  Red circles are the MPD estimates.}

\onefig{traceRecruits}{MCMC traces for recruitment estimates at five-year intervals. Note that vertical scales are different for each plot (to show convergence of the MCMC chain, rather than absolute differences in annual recruitment). Grey lines show the \numMCMC~samples for each parameter, solid lines show the cumulative  median (up to that sample), and dashed lines show the cumulative  2.5 and 97.5 quantiles.  Red circles are the MPD estimates.}

\onefig{pdfParameters}{Marginal posterior densities (thick black curves) and prior density functions (thin blue curves) for the estimated parameters. Vertical lines represent the 2.5, 50 and 97.5 percentiles, and red filled circles are the MPD estimates. For $R_0$ the prior is a uniform distribution on the range [1, 1e+05]. The priors for $q_g$ are uniform on a log-scale, and so the probability density function is $1/(x(b-a))$ on a linear scale (where $a$ and $b$ are the bounds on the log scale).}

\clearpage










\onefig{VBcatch}{Estimated vulnerable biomass (boxplots) and commercial catch (vertical bars), in tonnes, over time. Boxplots show the 2.5, 25, 50, 75 and 97.5 percentiles from the MCMC results. Catch is shown to compare its magnitude to the estimated vulnerable biomass.}

\onefig{BVBnorm}{Changes in $B_t / B_0$ and $V_t / V_0$ (spawning and vulnerable biomass relative to unfished equilibrium levels) over time, shown as the medians of the MCMC posteriors.}


\onefig{recruitsMCMC}{Marginal posterior distribution of recruitment in 1,000s of age-1 fish plotted over time. Boxplots show the 2.5, 25, 50, 75 and 97.5 percentiles from the MCMC results. Note that the first year for which there are age data is 1979, and the plus-age class is 32, such that there are no direct data concerning age-1 fish before 1948. Also, the final few years have no direct age-data from which to estimate recruitment, because fish are not fully selected until age 17.3 by the commercial vessels or age 15.6 by surveys (mean of the MCMC median ages at full selectivity for commercial catch, $\mu_{7}$, and survey $\mu_{1,2,3,4}$, respectively).}

\onefig{exploitMCMC}{Marginal posterior distribution of exploitation rate plotted over time. Boxplots show the 2.5, 25, 50, 75 and 97.5 percentiles from the MCMC results.}


\onefig{snail}{Phase plot through time of the medians of the ratios $B_t / B_\mathrm{MSY}$ (the spawning biomass in year $t$ relative to $B_\mathrm{MSY}$) and $u_t / u_\mathrm{MSY}$ (the exploitation rate in year $t$ relative to $u_\mathrm{MSY}$). Blue filled circle is the starting year (1940). Years then proceed from light grey through to dark grey with the final year (2013) as a filled red circle, and the red lines represent the 10\% and 90\% percentiles of the posterior distributions for the final year. Vertical grey lines indicate the Precautionary Approach provisional limit and upper stock reference points (0.4, 0.8 $B$msy), and horizontal grey line indicates $u$ at MSY.}% of 0.4$B_\\mathrm\{MSY\}$ and 0.8$B_\\mathrm\{MSY\}$, and horizontal grey line indicates $u_\\mathrm\{MSY\}$.")}}

\onefig{Bproj}{Projected biomass (t) under different constant catch strategies (t); boxplots show the 2.5, 25, 50, 75 and 97.5 percentiles from the MCMC results. For each of the \numMCMC~samples from the MCMC posterior, the model was run forward in time (red, with medians in black) with a constant catch, and recruitment was simulated from the stock-recruitment function with lognormal error (see Appendix~\eqnchapter). For reference, the average catch over the last 5 years (2009-2013) is 1431~t.}

\clearpage 

  

\clearpage     % to get tables at end
% Tables from MPD Run 16 Rwt 3

\begin{table}[!p]
\centering
\caption{\label{tab:like}  Negative log-likelihoods and objective function from the MPD results for the two models. Parameters and likelihood symbols are defined in Appendix F. For indices ($\hat{I}_{tg}$) and proportions-at-age ($\hat{p}_{atgs}$), subscripts $g=1...6$ refer to the trawl surveys and subscript $g=7+$ refers to the commercial fishery.}
\begin{tabular}{llr} 
\hline
Description & Negative log likelihood & Value \\
\hline \\[0.2pt]
Survey 1 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t1} \right\} \right)$ & -3.49\\[6pt]
Survey 2 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t2} \right\} \right)$ & -3.35\\[6pt]
Survey 3 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t3} \right\} \right)$ & -0.94\\[6pt]
Survey 4 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t4} \right\} \right)$ & 0.57\\[6pt]
Survey 5 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t5} \right\} \right)$ & 1.58\\[6pt]
Survey 6 & $\log \mbox{L}_{3} \left( \bfTh | \left\{ \hat{I}_{t6} \right\} \right)$ & 3.92\\[6pt]
CAs 1    & $\log \mbox{L}_{2} \left( \bfTh | \left\{ \hat{p}_{at1s} \right\} \right)$ & -282.71 \\[6pt] 
CAs 2    & $\log \mbox{L}_{2} \left( \bfTh | \left\{ \hat{p}_{at2s} \right\} \right)$ & -286.03 \\[6pt] 
CAs 3    & $\log \mbox{L}_{2} \left( \bfTh | \left\{ \hat{p}_{at3s} \right\} \right)$ & -415.58 \\[6pt] 
CAs 4    & $\log \mbox{L}_{2} \left( \bfTh | \left\{ \hat{p}_{at4s} \right\} \right)$ & -285.88 \\[6pt] 
CAc 1    & $\log \mbox{L}_{2} \left( \bfTh | \left\{ \hat{p}_{at7s} \right\} \right)$ & -3547.73 \\[6pt] 
Prior    & $\log \mbox{L}_{1} \left( \bfTh | \left\{ \epsilon_t \right\} \right) - \log \left( \pi( \bfTh ) \right)$ & 15.09 \\[6pt]  

\hline
~ & Objective function $f( \bfTh)$ & -4804.55 \\
\hline
\end{tabular}
\end{table}



% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[ht]
\centering
\caption{The 5\super{th}, 50\super{th}, and 95\super{th} percentiles for model parameters derived via MCMC estimation (defined in Appendix~\eqnchapter).} 
\label{tab:MCMCpar}
\begin{tabular}{crrr}
  \\[-1.0ex] \hline
 & 5\% & 50\% & 95\% \\ 
  \hline
$R_0$ & 3,153 & 4,194 & 5,492 \\ 
  $M_1$ & 0.05607 & 0.06324 & 0.06925 \\ 
  $M_2$ & 0.04563 & 0.05142 & 0.05743 \\ 
  $h$ & 0.5076 & 0.7499 & 0.9309 \\ 
  $q_1$ & 0.02467 & 0.03747 & 0.06008 \\ 
  $q_2$ & 0.007014 & 0.009638 & 0.01535 \\ 
  $q_3$ & 0.08021 & 0.1243 & 0.1944 \\ 
  $q_4$ & 0.01189 & 0.02107 & 0.03613 \\ 
  $q_5$ & 0.01513 & 0.02200 & 0.03185 \\ 
  $q_6$ & 0.02114 & 0.03290 & 0.05135 \\ 
  $\mu_1$ & 14.49 & 15.94 & 17.61 \\ 
  $\mu_2$ & 8.607 & 10.54 & 12.99 \\ 
  $\mu_3$ & 14.66 & 16.83 & 20.10 \\ 
  $\mu_4$ & 14.57 & 19.27 & 23.90 \\ 
  $\mu_7$ & 16.37 & 17.26 & 18.26 \\ 
  $\Delta_1$ & 0.1086 & 0.2186 & 0.3237 \\ 
  $\Delta_2$ & 0.1107 & 0.2219 & 0.3232 \\ 
  $\Delta_3$ & 0.1130 & 0.2187 & 0.3244 \\ 
  $\Delta_4$ & 0.1071 & 0.2161 & 0.3242 \\ 
  $\Delta_7$ & -0.002717 & 0.6623 & 1.259 \\ 
  $\mathrm{log} v_{1L}$ & 1.079 & 1.950 & 2.740 \\ 
  $\mathrm{log} v_{2L}$ & 1.171 & 2.178 & 3.111 \\ 
  $\mathrm{log} v_{3L}$ & 2.148 & 3.048 & 3.858 \\ 
  $\mathrm{log} v_{4L}$ & 3.276 & 4.263 & 4.949 \\ 
  $\mathrm{log} v_{7L}$ & 2.605 & 2.945 & 3.269 \\ 
   \hline
\end{tabular}
\end{table}
\clearpage

\begin{table}[tp]
\centering
\caption{\label{tab:MCMCderived} The 5$^\mathrm{th}$, 50$^\mathrm{th}$ and 95$^\mathrm{th}$ percentiles of MCMC-derived quantities from the \numMCMC~samples of the MCMC posterior. Definitions are: $B_0$ -- unfished equilibrium spawning biomass (mature females), $V_0$ -- unfished equilibrium vulnerable biomass (males and females), $B_{2014}$ -- spawning biomass at the start of $2014$, $V_{2014}$ -- vulnerable biomass in the middle of 2014, $u_{2013}$ -- exploitation rate (ratio of total catch to vulnerable biomass) in the middle of 2013, $u_\mathrm{max}$ -- maximum exploitation rate (calculated for each sample as the maximum exploitation rate from 1940-2013), $\Bmsy$ -- equilibrium spawning biomass at MSY (maximum sustainable yield), $u_\mathrm{MSY}$ -- equilibrium exploitation rate at MSY, $V_\mathrm{MSY}$ -- equilibrium vulnerable biomass at MSY. 
All biomass values (and MSY) are in tonnes. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.}
\begin{tabular}{lrrr} 
\\[-1.0ex]\hline
Value & \multicolumn{3}{c}{Percentile}\\
\cline{2-4}
 & 5\% & 50\% & 95\% \\
\hline 
 & & & \\
& \multicolumn{3}{c}{From model output}\\
$B_0$                  & 30,135 & 35,387 & 41,926 \\
$V_0$                  & 60,849 & 69,565 & 81,206 \\
$B_{2014}$             & 12,669 & 19,803 & 28,070 \\
$V_{2014}$             & 20,759 & 32,832 & 47,679 \\

$B_{2014} / B_0$       & 0.405 & 0.559 & 0.698 \\
$V_{2014} / V_0$     & 0.334 & 0.474 & 0.601 \\

$u_{2013}$             & 0.03 & 0.044 & 0.068 \\
\hline
 & & & \\
& \multicolumn{3}{c}{MSY-based quantities}\\
$B_\mathrm{MSY}$       &  7,089 & 9,718 & 13,717 \\
$0.4 B_\mathrm{MSY}$   &  2,836 & 3,887 & 5,487 \\
$0.8 B_\mathrm{MSY}$   &  5,671 & 7,774 & 10,974 \\
$B_{2014} / B_\mathrm{MSY}$ & 1.223 & 2.035 & 2.997 \\

$\mathrm{MSY}$                    & 1,299 & 1,998 & 2,688 \\
$u_\mathrm{MSY}$       & 0.064 & 0.145 & 0.3 \\
$u_{2013} / u_\mathrm{MSY}$ & 0.127 & 0.298 & 0.883 \\
\hline
\end{tabular}
\end{table}

\clearpage


% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table concerning the limit reference point $0.4 \Bmsy$ for 1-10 year projections for a range of constant catch strategies (in tonnes). Values are P$(B_t > 0.4 \Bmsy)$, i.e.~the probability of the spawning biomass (mature females) at the start of year $t$ being greater than the limit reference point. The probabilities are the proportion (to two decimal places) of the 1000 MCMC samples for which $B_t > 0.4 \Bmsy$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:LRP}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  2000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  2250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  2500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 \\ 
  2750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 \\ 
  3000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 \\ 
   \hline
\end{tabular}
\end{table}
% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table concerning the upper reference point $0.8 \Bmsy$ for 1-10 year projections, such that values are P$(B_t > 0.8 \Bmsy)$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:URP}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  1750 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  2000 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.98 & 0.98 \\ 
  2250 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 \\ 
  2500 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.98 & 0.98 & 0.98 & 0.97 & 0.97 & 0.96 \\ 
  2750 & 1.00 & 1.00 & 0.99 & 0.99 & 0.98 & 0.98 & 0.97 & 0.97 & 0.96 & 0.94 & 0.93 \\ 
  3000 & 1.00 & 1.00 & 0.99 & 0.99 & 0.98 & 0.97 & 0.96 & 0.95 & 0.93 & 0.92 & 0.89 \\ 
   \hline
\end{tabular}
\end{table}
% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table concerning the reference point $\Bmsy$ for 1-10 year projections, such that values are P$(B_t > \Bmsy)$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:Bmsy}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 0.99 & 0.99 & 0.99 & 0.99 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 1.00 & 1.00 & 1.00 \\ 
  750 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  1000 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  1250 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.98 & 0.98 \\ 
  1500 & 0.99 & 0.99 & 0.99 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 \\ 
  1750 & 0.99 & 0.99 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 & 0.98 & 0.97 & 0.97 & 0.97 \\ 
  2000 & 0.99 & 0.99 & 0.98 & 0.98 & 0.98 & 0.97 & 0.97 & 0.97 & 0.96 & 0.96 & 0.95 \\ 
  2250 & 0.99 & 0.99 & 0.98 & 0.98 & 0.97 & 0.96 & 0.96 & 0.95 & 0.94 & 0.93 & 0.92 \\ 
  2500 & 0.99 & 0.98 & 0.98 & 0.97 & 0.96 & 0.95 & 0.94 & 0.93 & 0.92 & 0.90 & 0.89 \\ 
  2750 & 0.99 & 0.98 & 0.97 & 0.96 & 0.95 & 0.94 & 0.93 & 0.91 & 0.88 & 0.87 & 0.85 \\ 
  3000 & 0.99 & 0.98 & 0.97 & 0.96 & 0.94 & 0.92 & 0.90 & 0.87 & 0.85 & 0.83 & 0.80 \\ 
   \hline
\end{tabular}
\end{table}
 \clearpage \pagebreak % latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table for comparing the projected biomass to the current biomass, given by probabilities P$(B_t > B_{\currYear})$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:Bcurr}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 0.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 0.00 & 1.00 & 1.00 & 0.99 & 0.99 & 1.00 & 0.99 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 0.00 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  750 & 0.00 & 0.98 & 0.96 & 0.96 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 \\ 
  1000 & 0.00 & 0.92 & 0.89 & 0.88 & 0.88 & 0.87 & 0.86 & 0.86 & 0.86 & 0.86 & 0.86 \\ 
  1250 & 0.00 & 0.81 & 0.77 & 0.74 & 0.72 & 0.71 & 0.70 & 0.71 & 0.71 & 0.71 & 0.72 \\ 
  1500 & 0.00 & 0.64 & 0.56 & 0.54 & 0.53 & 0.52 & 0.53 & 0.53 & 0.53 & 0.54 & 0.54 \\ 
  1750 & 0.00 & 0.43 & 0.37 & 0.35 & 0.35 & 0.36 & 0.37 & 0.37 & 0.38 & 0.38 & 0.37 \\ 
  2000 & 0.00 & 0.25 & 0.21 & 0.20 & 0.20 & 0.22 & 0.23 & 0.23 & 0.24 & 0.23 & 0.22 \\ 
  2250 & 0.00 & 0.15 & 0.13 & 0.12 & 0.12 & 0.12 & 0.13 & 0.14 & 0.14 & 0.14 & 0.13 \\ 
  2500 & 0.00 & 0.09 & 0.07 & 0.07 & 0.07 & 0.07 & 0.08 & 0.08 & 0.08 & 0.08 & 0.08 \\ 
  2750 & 0.00 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 \\ 
  3000 & 0.00 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 \\ 
   \hline
\end{tabular}
\end{table}% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table for comparing the projected exploitation rate to that at MSY, such that values are P$(u_t > u_\mathrm{MSY})$, i.e.~the probability of the exploitation rate in the middle of year $t$ being greater than that at MSY. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:umsy}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  250 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  500 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  750 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  1000 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 \\ 
  1250 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 \\ 
  1500 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 & 0.04 \\ 
  1750 & 0.06 & 0.06 & 0.06 & 0.06 & 0.06 & 0.07 & 0.07 & 0.07 & 0.07 & 0.08 & 0.08 \\ 
  2000 & 0.09 & 0.09 & 0.09 & 0.10 & 0.10 & 0.11 & 0.12 & 0.12 & 0.13 & 0.13 & 0.14 \\ 
  2250 & 0.12 & 0.12 & 0.12 & 0.14 & 0.15 & 0.16 & 0.17 & 0.19 & 0.20 & 0.21 & 0.21 \\ 
  2500 & 0.16 & 0.17 & 0.18 & 0.19 & 0.21 & 0.22 & 0.24 & 0.25 & 0.26 & 0.27 & 0.28 \\ 
  2750 & 0.20 & 0.22 & 0.23 & 0.25 & 0.27 & 0.28 & 0.30 & 0.31 & 0.33 & 0.35 & 0.36 \\ 
  3000 & 0.25 & 0.26 & 0.28 & 0.29 & 0.31 & 0.33 & 0.36 & 0.38 & 0.40 & 0.42 & 0.44 \\ 
   \hline
\end{tabular}
\end{table}
 \clearpage \pagebreak % latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table for the alternative limit reference point $0.2 B_0$ for 1-10 year projections, such that values are P$(B_t > 0.2 B_0)$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:B0_0.2}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  1750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  2000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  2250 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 \\ 
  2500 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.98 \\ 
  2750 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.99 & 0.98 & 0.97 \\ 
  3000 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.99 & 0.99 & 0.98 & 0.97 & 0.97 & 0.95 \\ 
   \hline
\end{tabular}
\end{table}
% latex table generated in R 3.0.2 by xtable 1.7-1 package
% Mon Nov 04 12:28:09 2013
\begin{table}[!ht]
\centering
\caption{Decision table for the alternative upper reference point $0.4 B_0$ for 1-10 year projections, such that values are P$(B_t > 0.4 B_0)$. For reference, the average catch over the last 5 years (2009-2013) is 1431~t.} 
\label{tab:B0_0.4}
\begin{tabular}{rrrrrrrrrrrr}
  \\[-1.0ex] \hline
 & 2014 & 2015 & 2016 & 2017 & 2018 & 2019 & 2020 & 2021 & 2022 & 2023 & 2024 \\ 
  \hline
0 & 0.96 & 0.97 & 0.98 & 0.99 & 0.99 & 0.99 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  250 & 0.96 & 0.97 & 0.98 & 0.98 & 0.99 & 0.99 & 0.99 & 1.00 & 1.00 & 1.00 & 1.00 \\ 
  500 & 0.96 & 0.97 & 0.98 & 0.98 & 0.98 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  750 & 0.96 & 0.97 & 0.97 & 0.98 & 0.98 & 0.98 & 0.98 & 0.99 & 0.99 & 0.99 & 0.99 \\ 
  1000 & 0.96 & 0.96 & 0.97 & 0.97 & 0.97 & 0.97 & 0.97 & 0.98 & 0.98 & 0.98 & 0.98 \\ 
  1250 & 0.96 & 0.96 & 0.96 & 0.96 & 0.96 & 0.96 & 0.96 & 0.96 & 0.97 & 0.97 & 0.97 \\ 
  1500 & 0.96 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 & 0.95 & 0.94 & 0.94 & 0.94 \\ 
  1750 & 0.96 & 0.95 & 0.95 & 0.94 & 0.93 & 0.93 & 0.92 & 0.92 & 0.91 & 0.91 & 0.90 \\ 
  2000 & 0.96 & 0.95 & 0.94 & 0.93 & 0.91 & 0.90 & 0.89 & 0.88 & 0.86 & 0.85 & 0.84 \\ 
  2250 & 0.96 & 0.94 & 0.92 & 0.90 & 0.88 & 0.86 & 0.84 & 0.82 & 0.81 & 0.79 & 0.77 \\ 
  2500 & 0.96 & 0.94 & 0.91 & 0.88 & 0.86 & 0.83 & 0.80 & 0.78 & 0.75 & 0.72 & 0.69 \\ 
  2750 & 0.96 & 0.93 & 0.89 & 0.86 & 0.83 & 0.79 & 0.77 & 0.72 & 0.69 & 0.66 & 0.62 \\ 
  3000 & 0.96 & 0.93 & 0.88 & 0.85 & 0.80 & 0.76 & 0.71 & 0.66 & 0.62 & 0.57 & 0.53 \\ 
   \hline
\end{tabular}
\end{table}
 \clearpage \pagebreak 


\clearpage
% End of Appendix G


\end{document}
